### ISSUE TITLE
BUG package.json

### ISSUE THREAD

**Issue by matgott** [koolamusic/chakra-ui-autocomplete#55]
Hi folks, I'm triying to use this lib with Vitejs + react + typescript but I receive an error when I import the module

"The package may have incorrect main/module/exports specified in its package.json"

For me the problem was that in package.json the "module" property refer to a nonexistent file "index.modern.js", after change it to "index.js" it started to work.

{
	"name": "chakra-ui-autocomplete",
	"version": "1.4.1",
	"description": "An accessible autocomplete utility library built for chakra UI",
	"author": "Andrew Miracle <me@andrewmiracle.com>",
	"license": "MIT",
	"main": "dist/index.js",
	"typings": "dist/index.d.ts",
	**"module": "dist/index.modern.js",**
	"source": "src/index.tsx",
	"engines": {
		"node": ">=10"
	},
	"scripts": {
		"start": "tsdx watch",
		"build": "rimraf dist && tsdx build",
		"test": "tsdx test",
		"test:tsc": "tsc --pretty --noEmit",
		"prepare": "run-s build",
		"test:build": "run-s build",
		"test:lint": "eslint ./src --ext ts --ext tsx --fix",
		"test:unit": "cross-env CI=1 react-scripts test --env=jsdom",
		"test:watch": "react-scripts test --env=jsdom",
		"predeploy": "cd example && npm install && npm run build",
		"deploy": "gh-pages -d example/build"
	},
	"peerDependencies": {
		"@chakra-ui/react": ">= 1.0.0",
		"framer-motion": ">= 2.9.4",
		"react": ">= 16.8.1"
	},
	"devDependencies": {
		"@chakra-ui/react": "^1.0.1",
		"@emotion/react": "^11.1.1",
		"@emotion/styled": "^11.0.0",
		"@testing-library/jest-dom": "^4.2.4",
		"@testing-library/react": "^9.5.0",
		"@testing-library/user-event": "^7.2.1",
		"@types/jest": "^25.1.4",
		"@types/match-sorter": "^4.0.0",
		"@types/node": "^12.12.38",
		"@types/react": "^16.9.27",
		"@types/react-dom": "^16.9.7",
		"@types/react-highlight-words": "^0.16.1",
		"@types/react-test-renderer": "^16.9.3",
		"@typescript-eslint/eslint-plugin": "^2.26.0",
		"@typescript-eslint/parser": "^2.26.0",
		"cross-env": "^7.0.2",
		"eslint": "^6.8.0",
		"eslint-config-prettier": "^6.7.0",
		"eslint-config-standard": "^14.1.0",
		"eslint-plugin-import": "^2.18.2",
		"eslint-plugin-node": "^11.0.0",
		"eslint-plugin-prettier": "^3.1.1",
		"eslint-plugin-react": "^7.17.0",
		"framer-motion": "^2.9.4",
		"gh-pages": "^2.2.0",
		"npm-run-all": "^4.1.5",
		"prettier": "^2.0.4",
		"react": "^16.13.1",
		"react-dom": "^16.13.1",
		"react-scripts": "^4.0.3",
		"react-test-renderer": "^17.0.1",
		"rimraf": "^3.0.2",
		"tsdx": "^0.14.1",
		"tslib": "^2.0.3",
		"typescript": "^3.7.5"
	},
	"files": [
		"dist"
	],
	"publishConfig": {
		"access": "public"
	},
	"keywords": [
		"Chakra UI",
		"downshift",
		"autocomplete",
		"combobox",
		"react",
		"chakra-ui",
		"multiselect-chakra-ui"
	],
	"repository": {
		"type": "git",
		"url": "git+https://github.com/koolamusic/chakra-ui-autocomplete.git"
	},
	"dependencies": {
		"@chakra-ui/icons": "^1.0.3",
		"downshift": "^6.0.6",
		"match-sorter": "^4.2.1",
		"react-highlight-words": "^0.16.0",
		"react-use": "^15.3.4"
	}
}

**Comment by koolamusic** [comment]
correct. this module initially used `rollup` to bundle the package before I moved to `tsdx` will confirm and update

**Comment by koolamusic** [comment]
this has been fixed in `v1.4.2` 

Please let me know if this works for you

**Comment by matgott** [comment]
> 
> 
> this has been fixed in `v1.4.2`
> 
> Please let me know if this works for you

Re-installing through npm should work? 'cause not for me, it still installing old version.

**Comment by L2Develop96** [comment]
@koolamusic  still persists in v1.4.5.

I'm using the following versions: 
```
"@emotion/react": "^11.10.6,
"@chakra-ui/react": "^2.5.3"
```
